site_name: MathWallet Doc
site_description: In Math We Trust!
site_author: MathWallet


site_url: http://doc.mathwallet.org/
repo_url: https://github.com/MediShares/mds-help

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathWallet

pages:
    - Home: index.md
    - 中文:
        - EOS: cn/eos.md
        - ETH: cn/eth.md
        - TRON: cn/tron.md
        - ONT: cn/ont.md
        - BTC: cn/btc.md
        - NEO: cn/neo.md
        - EOS原力: cn/eosforce.md
        - 更多问题: cn/more.md
    - English:
        - EOS: en/eos.md
        - ETH: en/eth.md
        - TRON: en/tron.md
        - ONT: en/ont.md
        - BTC: en/btc.md
        - NEO: en/neo.md
        - EOSForce: en/eosforce.md
        - More: en/more.md

plugins:
    - search